version: 0.1

phases:
  build:
    commands:
      - echo Entered the build phase ...
      - mvn clean package

    post_build:
      commands:
        - echo Build Completed successfully

artifacts:
  files:
    - target/aws-pipeline-0.0.1-SNAPSHOT.jar

  discard-paths: yes